version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: crud-kotlin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: crud-kotlin
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db

volumes:
  postgres_data: